/* BerryBox application. AwsService is the only place that needs AWS-specific work. */
const cfg = window.BERRYBOX_CONFIG || { demoMode: true };
const seedPhotos = [
  ['Friends together','public/Frame-16@2x.png','People'],['Tennis afternoon','public/Frame-14@2x.png','Sport'],
  ['Blue classic','public/Frame-15@2x.png','Travel'],['A good read','public/Frame-18@2x.png','Pets'],
  ['Beach day','public/Frame-17@2x.png','Travel'],['Music break','public/Frame-19@2x.png','People']
].map(([name,url,category],i)=>({id:String(i+1),name,url,category,favorite:i===0||i===2||i===4,createdAt:'2026-09-04',size:3200000+i*190000}));
const store = {get(k, fallback){try{return JSON.parse(localStorage.getItem(k))||fallback}catch{return fallback}},set(k,v){localStorage.setItem(k,JSON.stringify(v))}};
class AwsService {
  constructor(){this.demo=cfg.demoMode;this.token=store.get('berry-token','');}
  headers(){return {'Content-Type':'application/json',...(this.token?{Authorization:`Bearer ${this.token}`}:{})};}
  async request(path, options={}){const res=await fetch(`${cfg.apiBaseUrl}${path}`,{...options,headers:{...this.headers(),...(options.headers||{})}});if(!res.ok)throw new Error(`Request failed (${res.status})`);return res.status===204?null:res.json();}
  async signIn({email}){if(this.demo){this.token='demo-session';store.set('berry-token',this.token);store.set('berry-user',{name:email.split('@')[0]||'BerryBox member',email,memberSince:new Date().toLocaleString('en-US',{month:'long',year:'numeric'})});return;}throw new Error('Connect Cognito Hosted UI or SDK in AwsService.signIn.');}
  async signUp(data){if(this.demo){await this.signIn(data);return;}throw new Error('Connect Cognito Hosted UI or SDK in AwsService.signUp.');}
  async photos(){return this.demo?store.get('berry-photos',seedPhotos):this.request('/photos');}
  async savePhotos(p){if(this.demo)store.set('berry-photos',p);}
  async profile(){return this.demo?store.get('berry-user',{name:'BerryBox member',email:'member@example.com',quotaBytes:10e9,memberSince:'September 2026'}):this.request('/profile');}
  async upload(file){if(this.demo){return {id:crypto.randomUUID(),name:file.name.replace(/\.[^/.]+$/,''),url:URL.createObjectURL(file),category:'Unsorted',favorite:false,createdAt:new Date().toISOString().slice(0,10),size:file.size};}const ticket=await this.request('/uploads',{method:'POST',body:JSON.stringify({name:file.name,type:file.type,size:file.size})});await fetch(ticket.uploadUrl,{method:'PUT',headers:{'Content-Type':file.type},body:file});return this.request('/photos',{method:'POST',body:JSON.stringify({key:ticket.key,name:file.name,size:file.size})});}
  async updatePhoto(id,patch){if(!this.demo)return this.request(`/photos/${id}`,{method:'PATCH',body:JSON.stringify(patch)});}
  async deletePhoto(id){if(!this.demo)return this.request(`/photos/${id}`,{method:'DELETE'});}
  // Returns a URL the browser can fetch the ORIGINAL image bytes from, for the download action.
  // Demo mode: the photo's own url (local asset or object URL) already points at the original file.
  // Live mode: prefer an originalUrl the /photos payload may already carry; otherwise ask the
  // backend for a fresh presigned S3 GetObject URL scoped to the original (non-resized) object.
  // Backend contract to add if you don't have it yet: GET /photos/:id/download -> { url }
  async downloadUrl(photo){
    if(this.demo) return photo.url;
    if(photo.originalUrl) return photo.originalUrl;
    const ticket = await this.request(`/photos/${photo.id}/download`);
    return ticket.url;
  }
}
const api=new AwsService(), app=document.querySelector('#app'), fileInput=document.querySelector('#file-input');
let state={route:location.hash.slice(1)||'home',photos:[],profile:null,search:'',category:'all',draft:null};
const esc=s=>String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const bytes=n=>n>1e9?`${(n/1e9).toFixed(2)} GB`:`${(n/1e6).toFixed(1)} MB`;
function usageStats(){const used=state.photos.reduce((n,p)=>n+(p.size||0),0),quota=10e9;return {used,quota,percent:Math.min(100,quota?used/quota*100:0)};}
function go(route){location.hash=route;}
function toast(message){const el=document.createElement('div');el.className='toast';el.textContent=message;document.body.append(el);setTimeout(()=>el.remove(),2800);}
function landing(){return `<main class="landing modern-landing"><section class="welcome"><div class="welcome-brand"><img class="logo" src="public/cib-raspberry-pi.png" alt="BerryBox logo"><div class="brand">BerryBox</div></div><span class="eyebrow">YOUR PRIVATE PHOTO SPACE</span><h1>Keep the moments<br>that matter <em>close.</em></h1><p>A calm, beautiful home for every photo and every little memory.</p><div class="hero-actions"><button class="btn" data-go="signup">Create your gallery <span>→</span></button><button class="text-button" data-go="signin">I already have an account</button></div></section><section class="hero-gallery"><img class="hero-main" src="public/Frame-16@2x.png" alt="Friends making memories"><img class="hero-float first" src="public/Frame-14@2x.png" alt="Tennis memory"><img class="hero-float second" src="public/Frame-19@2x.png" alt="Music memory"><div class="memory-note">✦ <strong>12,548</strong> memories<br><small>saved safely</small></div></section></main>`}
function auth(kind){let signup=kind==='signup';return `<main class="auth modern-auth"><section class="auth-side"><div class="auth-brand"><img class="logo" src="public/cib-raspberry-pi.png" alt=""><div class="brand">BerryBox</div></div><div class="auth-copy"><span class="eyebrow">YOUR PRIVATE PHOTO SPACE</span><h1>Every memory<br>deserves a home.</h1><p>Keep the people, places and moments you love beautifully organised and always within reach.</p></div><div class="auth-image"><img src="public/Frame-17@2x.png" alt="A favorite memory"></div></section><section class="auth-card"><form class="form-box" id="auth-form"><span class="eyebrow">${signup?'START YOUR COLLECTION':'WELCOME BACK'}</span><h2>${signup?'Create your account':'Sign in to BerryBox'}</h2><p class="form-intro">${signup?'Your memories are waiting for a place to live.':'Your photos are right where you left them.'}</p>${cfg.demoMode?'<div class="notice">Demo mode: use any email and password.</div>':''}${signup?'<div class="field"><label for="name">Full name</label><input id="name" required placeholder="Your name"></div>':''}<div class="field"><label for="email">Email address</label><input id="email" type="email" required placeholder="you@example.com"></div><div class="field"><label for="password">Password</label><input id="password" type="password" required minlength="6" placeholder="At least 6 characters"></div>${signup?'<label class="agreement"><input type="checkbox" required> I agree to the processing of my personal data</label>':''}<button class="btn" type="submit">${signup?'Create my gallery':'Sign in'} <span>→</span></button><p class="switch-auth">${signup?'Already have an account?':'New to BerryBox?'} <button class="form-link" type="button" data-go="${signup?'signin':'signup'}">${signup?'Sign in':'Create an account'}</button></p></form></section></main>`}
function shell(body, route){let nav=[['gallery','public/solar_gallery-linear.svg','Gallery'],['upload','public/tabler_photo-plus.svg','Upload'],['favorites','public/tabler_photo-star.svg','Favorites'],['profile','public/iconamoon_profile-light.svg','Profile']];return `<div class="shell"><header class="topbar"><div class="top-brand"><img class="logo" src="public/cib-raspberry-pi.png" alt="BerryBox"><div class="brand">BerryBox</div></div><div class="search-wrap"><img src="public/iconamoon_search-thin.svg" alt=""><input class="search" id="search" value="${esc(state.search)}" placeholder="Search your memories"></div><div class="top-actions"><button class="bell" title="Notifications"><img src="public/streamline-flex-color_bell-notification-flat.svg" alt="Notifications"></button><button class="avatar" data-go="profile" title="Profile"><img src="public/bi_person-circle.svg" alt="Profile"></button></div></header><nav class="nav">${nav.map(([id,icon,label])=>`<button class="${route===id?'active':''}" data-go="${id}"><img src="${icon}" alt="">${label}</button>`).join('')}<button class="logout" data-action="logout">Logout</button></nav>${body}<footer class="footer">© 2026 BerryBox · Your memories, beautifully kept.</footer></div>`}
function photoCard(p){return `<article class="photo"><button class="star ${p.favorite?'on':''}" data-action="favorite" data-id="${p.id}" aria-label="${p.favorite?'Remove from favorites':'Add to favorites'}">★</button><button class="icon-chip dl" data-action="download" data-id="${p.id}" title="Download" aria-label="Download photo"><img src="public/tabler_download.svg" alt=""></button><button class="icon-chip del" data-action="ask-delete" data-id="${p.id}" title="Delete" aria-label="Delete photo"><img src="public/tabler_trash.svg" alt=""></button><button class="photo" data-action="details" data-id="${p.id}"><img src="${esc(p.url)}" alt="${esc(p.name)}"><div class="caption">${esc(p.name)}</div></button></article>`}
function sidePanel(){let {used,quota,percent}=usageStats();return `<aside class="side"><section class="panel"><h2>Upload new photo</h2><div id="drop-zone" class="drop"><p>Drag & drop a photo here<br>or click to browse</p><button class="btn" data-action="choose">Choose file</button><small><br><br>JPG, PNG, WebP up to 10 MB</small>${state.draft?`<img class="upload-preview" src="${state.draft.url}" alt="Upload preview"><button class="btn" style="width:100%;margin-top:12px" data-action="save-upload">Upload “${esc(state.draft.name)}”</button>`:''}</div></section><section class="panel"><h2>Storage overview</h2><div class="stats"><div><span>${bytes(used)} / ${bytes(quota)} used</span><span>${percent.toFixed(0)}%</span></div></div><div class="bar"><span style="width:${percent}%"></span></div></section><section class="panel"><h2>Quick info</h2><div class="stats"><div><span>Photos uploaded</span><span>${state.photos.length}</span></div><div><span>Member since</span><span>${esc(state.profile?.memberSince||'September 2026')}</span></div><div><span>Total storage</span><span>10 GB</span></div></div></section></aside>`}
function gallery(favorites=false){let list=state.photos.filter(p=>(!favorites||p.favorite)&&(!state.search||p.name.toLowerCase().includes(state.search.toLowerCase()))&&(state.category==='all'||p.category===state.category));let categories=[...new Set(state.photos.map(p=>p.category))];return shell(`<main class="page"><div class="page-grid"><section class="panel"><div class="panel-head"><h1>${favorites?'Favorites':'Gallery'}</h1><div class="filters"><span>Filter:</span><select id="category"><option value="all">All categories</option>${categories.map(c=>`<option ${state.category===c?'selected':''}>${esc(c)}</option>`).join('')}</select></div></div><div class="grid">${list.length?list.map(photoCard).join(''):`<div class="empty">No photos found. Try a different search or upload a new memory.</div>`}</div></section>${sidePanel()}</div></main>`,favorites?'favorites':'gallery')}
function upload(){return shell(`<main class="page"><div class="page-grid"><section class="panel"><div class="panel-head"><h1>Upload a photo</h1></div><p class="meta">Your original is stored privately. The gallery displays the optimised version created by Lambda.</p><div id="drop-zone" class="drop" style="padding:70px 20px"><p>Drop a photo here, or select it from your device.</p><button class="btn" data-action="choose">Choose photo</button>${state.draft?`<img class="upload-preview" src="${state.draft.url}" alt=""><div class="profile-actions"><button class="btn" data-action="save-upload">Upload photo</button><button class="btn secondary" data-action="cancel-upload">Cancel</button></div>`:''}</div></section>${sidePanel()}</div></main>`,'upload')}
function profile(){let p=state.profile||{};let {used,quota}=usageStats();return shell(`<main class="page"><section class="panel profile"><div class="profile-header"><div class="big-avatar">◕</div><div><h1>${esc(p.name||'BerryBox member')}</h1><div class="meta">${esc(p.email||'member@example.com')}</div></div></div><form id="profile-form"><div class="field"><label>Display name</label><input id="profile-name" value="${esc(p.name||'')}"></div><div class="field"><label>Email</label><input value="${esc(p.email||'')}" disabled></div><div class="profile-actions"><button class="btn" type="submit">Save profile</button><button class="btn secondary" type="button" data-go="gallery">Back to gallery</button></div></form><div class="stats" style="margin-top:26px"><div><span>Member since</span><span>${esc(p.memberSince||'—')}</span></div><div><span>Photos uploaded</span><span>${state.photos.length}</span></div><div><span>Storage used</span><span>${bytes(used)} / ${bytes(quota)}</span></div></div></section></main>`,'profile')}
function modal(p){return `<div class="modal" data-action="close-modal"><section class="modal-card" onclick="event.stopPropagation()"><button class="modal-close" data-action="close-modal">×</button><img src="${esc(p.url)}" alt="${esc(p.name)}"><div class="photo-details"><h2>${esc(p.name)}</h2><div class="meta">${esc(p.category)} · Uploaded ${esc(p.createdAt)} · ${bytes(p.size)}</div><div class="profile-actions"><button class="btn secondary" data-action="download" data-id="${p.id}">⬇ Download</button><button class="btn secondary" data-action="favorite" data-id="${p.id}">${p.favorite?'★ Remove from favorites':'☆ Add to favorites'}</button><button class="btn danger" data-action="ask-delete" data-id="${p.id}">Delete photo</button></div></div></section></div>`}
function confirmDeleteModal(p){return `<div class="modal" data-action="close-modal"><section class="modal-card" style="max-width:420px" onclick="event.stopPropagation()"><button class="modal-close" data-action="close-modal">×</button><div class="photo-details"><h2>Delete this photo?</h2><p class="meta">“${esc(p.name)}” will be permanently removed from your gallery and storage. This can't be undone.</p><div class="profile-actions"><button class="btn secondary" data-action="close-modal">Cancel</button><button class="btn danger" data-action="confirm-delete" data-id="${p.id}">Delete photo</button></div></div></section></div>`}
async function render(){state.route=location.hash.slice(1)||'home';if(['gallery','favorites','upload','profile'].includes(state.route)&&!api.token){go('signin');return;}if(['gallery','favorites','upload','profile'].includes(state.route)){state.photos=await api.photos();state.profile=await api.profile();}let views={home:landing,signin:()=>auth('signin'),signup:()=>auth('signup'),gallery:()=>gallery(),favorites:()=>gallery(true),upload,profile};app.innerHTML=(views[state.route]||landing)();}
async function chooseFile(file){if(!file)return;if(!file.type.startsWith('image/')||file.size>10*1024*1024){toast('Choose an image smaller than 10 MB.');return;}state.draft={file,name:file.name.replace(/\.[^/.]+$/,''),url:URL.createObjectURL(file)};render();}
function guessExtension(url, mime){const fromUrl=(url.split('?')[0].match(/\.[a-zA-Z0-9]+$/)||[])[0];if(fromUrl)return fromUrl;const map={'image/jpeg':'.jpg','image/png':'.png','image/webp':'.webp','image/gif':'.gif'};return map[mime]||'';}
async function downloadPhoto(p){try{const url=await api.downloadUrl(p);const res=await fetch(url);if(!res.ok)throw new Error('Could not download this photo.');const blob=await res.blob();const ext=guessExtension(url,blob.type);const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`${p.name||'photo'}${ext}`;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(a.href),4000);}catch(err){toast(err.message||'Download failed.');}}
document.addEventListener('click',async e=>{let b=e.target.closest('[data-go],[data-action]');if(!b)return;if(b.dataset.go){go(b.dataset.go);return;}let action=b.dataset.action,id=b.dataset.id;if(action==='logout'){api.token='';store.set('berry-token','');go('home')}if(action==='choose')fileInput.click();if(action==='cancel-upload'){state.draft=null;render()}if(action==='save-upload'&&state.draft){try{let photo=await api.upload(state.draft.file);state.photos.unshift(photo);await api.savePhotos(state.photos);state.draft=null;toast('Photo uploaded successfully.');go('gallery')}catch(err){toast(err.message)}}if(action==='favorite'){let p=state.photos.find(x=>x.id===id);p.favorite=!p.favorite;await api.updatePhoto(id,{favorite:p.favorite});await api.savePhotos(state.photos);render()}if(action==='details'){let p=state.photos.find(x=>x.id===id);document.body.insertAdjacentHTML('beforeend',modal(p))}if(action==='download'){let p=state.photos.find(x=>x.id===id);if(p)await downloadPhoto(p)}if(action==='ask-delete'){let p=state.photos.find(x=>x.id===id);if(p)document.body.insertAdjacentHTML('beforeend',confirmDeleteModal(p))}if(action==='confirm-delete'){try{await api.deletePhoto(id);let wasFavorite=state.photos.find(x=>x.id===id)?.favorite;state.photos=state.photos.filter(p=>p.id!==id);await api.savePhotos(state.photos);document.querySelector('.modal')?.remove();render();toast(wasFavorite?'Photo deleted and removed from favorites.':'Photo deleted.')}catch(err){toast(err.message||'Could not delete this photo.')}}if(action==='close-modal')document.querySelector('.modal')?.remove();});
document.addEventListener('submit',async e=>{if(e.target.id==='auth-form'){e.preventDefault();try{let data=Object.fromEntries(new FormData(e.target));if(state.route==='signup')await api.signUp(data);else await api.signIn(data);toast('Welcome to BerryBox!');go('gallery')}catch(err){toast(err.message)}}if(e.target.id==='profile-form'){e.preventDefault();let p=await api.profile();p.name=document.querySelector('#profile-name').value.trim()||p.name;state.profile=p;store.set('berry-user',p);toast('Profile saved.');render()}});
document.addEventListener('input',e=>{if(e.target.id==='search'){state.search=e.target.value;render().then(()=>{let search=document.querySelector('#search');search?.focus();search?.setSelectionRange(state.search.length,state.search.length)})}});document.addEventListener('change',e=>{if(e.target.id==='category'){state.category=e.target.value;render()}});fileInput.addEventListener('change',e=>chooseFile(e.target.files[0]));document.addEventListener('dragover',e=>{if(e.target.closest('#drop-zone'))e.preventDefault()});document.addEventListener('drop',e=>{if(e.target.closest('#drop-zone')){e.preventDefault();chooseFile(e.dataTransfer.files[0])}});window.addEventListener('hashchange',render);render();
